
title: Ícaro Harry - Resumé
url: 'http://github.com/icaroharry'
baseurl: '/' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Ícaro Harry
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: icaropc17@gmail.com
linkedin: icaroharry
github: icaroharry
twitter: '@icaroharry'


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
